title: SoyDeveloper And Nerdito
description: Mainly development stuff, software or hardware
author: Soynerdito
github: https://github.com/soynerdito
about: Computer Engineer working as a developer. Love to keep on learning new stuff and enjoying sharing. Interest change frequently what forces me to keep on learning new stuff.
disqus_shortname: soynerdito
google_analytics: 

enableTags: true
tagarray: []

collections:
  project:
    output: true
    permalink: /project/:path/

social:
    # - icon: fa-facebook
    #   link: "#"
    - icon: fa-twitter
      link: "https://twitter.com/soynerdito"
    # - icon: fa-linkedin
    #   link: "#"
    # - icon: fa-stack-exchange
    #   link: "#"
    - icon: fa-github
      link: "https://github.com/soynerdito"

share:
  twitter_username: github.io
  fb_appid: 

urls:
    - text: About Me
      url: /about/
    - text: My Projects
      url: /projects/
    - text: XML Feed
      url: /feed.xml

url: "https://soynerdito.github.io"
baseurl: ""
paginate: 20
per_page: 20
paginate_path: "/page/:num/"
markdown: kramdown
gems:
  - jekyll-paginate
  - jekyll-gist

compress_html:
  clippings: all
  comments: ["<!-- ", " -->"]
  endings: all
  ignore:
    envs: ['development']
